"""
Module containing mapping between different classification schemes
"""
import numpy as np

tns_map = {
    None: None,
    "SN IIP": "SN II",
    "SN IIn": "SN II",
    "SN Ia": "SN Ia",
    "SN Ib/c": "SN Ib/c",
    "SN Ia-pec": "SN Ia",
    "TDE-H-He": "TDE",
    "SN Ia-91T-like": "SN Ia",
    "LBV": "Varstar",
    "Other": None,
    "QSO": "AGN",
    "SN II": "SN II",
    "SN Ibn": "SN Ib/c",
    "SN I": "SN Ib/c",
    "TDE": "TDE",
    "SN IIb": "SN II",
    "SN Ia-91bg-like": "SN Ia",
    "Varstar": "Varstar",
    "SN Ib": "SN Ib/c",
    "SN Ia-CSM": "SN Ia",
    "SLSN-II": "SLSN",
    "CV": "Varstar",
    "AGN": "AGN",
    "SN Ic": "SN Ib/c",
    "SN Ic-BL": "SN Ib/c",
    "SN": "SN",
    "SN Iax[02cx-like]": "SN Ia",
    "Galaxy": "Galaxy",
    "SLSN-I": "SLSN",
    "SN Ia-SC": "SN Ia",
}

bts_map = {
    "SN IIP": "SN II",
    "SN IIn": "SN II",
    "SN Ia": "SN Ia",
    "SN Ia-91bg": "SN Ia",
    "SN Ia-pec": "SN Ia",
    "AGN?": "AGN",
    "SN II": "SN II",
    "SN Ibn": "SN Ib/c",
    "CV?": "Varstar",
    "TDE": "TDE",
    "SN IIb": "SN II",
    "SN Iax": "SN Ia",
    "SN Ib": "SN Ib/c",
    "SLSN-II": "SLSN",
    "CV": "Varstar",
    "AGN": "AGN",
    "SN Ia-91T": "SN Ia",
    "SN Ic": "SN Ib/c",
    "SN Ic-BL": "SN Ib/c",
    "other": "other",
    None: None,
    "SLSN-I": "SLSN",
    "NLSy1?": "AGN",
    "AM CVn": "Varstar",
    "NLS1": "AGN",
    "blazar": "AGN",
    "Galactic Nuclei": None,
    "duplicate": None,
    "QSO": "AGN",
    "CLAGN": "AGN",
    "SN II?": "SN II",
    "bogus": "bogus",
    "SN Ia?": "SN Ia",
    "SN IIn?": "SN II",
    "bogus?": "bogus",
    "SN Ia-03fg": "SN Ia",
    "Seyfert": "AGN",
    "star": "Varstar",
    "SLSN-I?": "SLSN",
    "SN Ia-CSM": "SN Ia",
    "Other": "???",
    "SN Ia-SC": "SN Ia",
    np.nan: None,
    "nan": None,
}

fritz_map = {
    "transient": "transient",
    "bogus": "bogus",
    "Ib": "SN Ib/c",
    "Ia-91bg": "SN Ia",
    "Stellar variable": "Varstar",
    "Ia-norm": "SN Ia",
    "IIb": "SN II",
    "IIP": "SN II",
    "Ic": "SN Ib/c",
    "Supernova": "SN",
    "Type II": "SN II",
    "SLSN I": "SLSN",
    "varstar": "Varstar",
    "Cataclysmic": "Varstar",
    "Tidal Disruption Event": "TDE",
    "Ic-SLSN": "SLSN",
    "BL Lac": "AGN",
    "Ic-BL": "SN Ib/c",
    "Ia-91T": "SN Ia",
    "II-norm": "SN II",
    "QSO": "AGN",
    "Ia-03fg": "SN Ia",
    "Ia-CSM": "SN Ia",
    "AM CVn": "Varstar",
    "Blazar": "AGN",
    "IIn": "SN II",
    "Ibn": "SN Ib/c",
    "Type I": "SN Ib/c",
    "Seyfert": "AGN",
    "Ia-pec": "SN Ia",
    "Ia-18byg": "SN Ia",
    None: None,
    "Ib/c": "SN Ib/c",
    "Ia-02cx": "SN Ia",
    "duplicate": None,
    "AGN": "AGN",
    "Ia": "SN Ia",
    "U Gem": "Varstar",
    "Galactic Nuclei": None,
    "Pulsating": "Varstar",
    "II-pec": "SN II",
    "II-SLSN": "SLSN",
    "Mira": "Varstar",
    "LPV": "Varstar",
    "S Doradus": "Varstar",
}

growth_map = {
    "QSO?": "AGN",
    "unclassified": "unclassified",
    "SN IIP": "SN II",
    "SN Ia pec": "SN Ia",
    "SN? ": "SN",
    "CV": "Varstar",
    "LBV": "Varstar",
    "SN II": "SN II",
    "SN Ia 91T": "SN Ia",
    "var": "Variable",
    "SN Ib/c": "SN Ib/c",
    "CV?": "Varstar",
    "blazar": "AGN",
    "SN": "SN",
    "duplicate": None,
    "SN Ic-BL": "SN Ib/c",
    "AGN?": "AGN",
    "Ia": "SN Ia",
    "SN Ia ": "SN Ia",
    "SN Ia-CSM": "SN Ia",
    "LINER": "AGN",
    "SN Ib": "SN Ib",
    "SN Ia": "SN Ia",
    "SN Ia-91bg": "SN Ia-91bg",
    "TDE?": None,
    "SN Ia?": "SN Ia",
    "SN Ib?": "SN Ib/c",
    "varstar?": "Varstar",
    "SLSN-II?": "SLSN",
    "varstar": "Varstar",
    "SNIa": "SN Ia",
    "SN Ia-pec": "SN Ia",
    "SN IIn": "SN II",
    "AGN? ": "AGN",
    "SNIIn?": "SN II",
    "SN Ia-csm": "SN Ia",
    "SLSN-I": "SLSN",
    "SNII": "SN II",
    "SN Ic?": "SN Ib/c",
    "SN Ibn": "SN Ib/c",
    "unknown": None,
    "NLS1": "AGN",
    "SN Ia-91T": "SN Ia",
    "stellar?": "Varstar",
    "SN Ia-norm": "SN Ia",
    "SLSN-II": "SLSN",
    "Ic-BL": "SN Ib/c",
    "star": "Varstar",
    "blazar?": "AGN",
    "SNIc?": "SN Ib/c",
    "star?": "Varstar",
    "SN Ia 91T-like": "SN Ia",
    "AGN": "AGN",
    "SN II?": "SN II",
    "SLSN-I?": "SLSN",
    "SN?": "SN",
    "SN IIb": "SN II",
    "AGN ": "AGN",
    "quasar": "AGN",
    "SN Ia 03fg-like": "SN Ia",
    "TDE": "TDE",
    "TDE? ": "TDE",
    "CLAGN": "AGN",
    "SN IIn?": "SN II",
    "Gap I": "Gap I",
    "bogus?": "bogus",
    "bogus": "bogus",
    "galaxy": None,
    "SLSN?": "SLSN",
    None: None,
    "QSO": "AGN",
    "SN Ic": "SN Ib/c",
    "NLSy1?": "AGN",
    "SLSN-R": "SLSN",
    "stars": "Varstar",
    "Q": "AGN",
    "CV Candidate": "Varstar",
    "M-star": "Varstar",
    "SNII?": "SN II",
    "XRB": "Varstar",
    "SNIc": "SN Ib/c",
}
